################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (13.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Augmented.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Setup.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Transport.c 

OBJS += \
./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.o \
./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.o \
./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.o \
./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.o \
./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.o \
./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.o \
./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.o \
./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.o \
./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.o \
./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.o \
./Invn/Devices/Drivers/Icm20948/Icm20948Setup.o \
./Invn/Devices/Drivers/Icm20948/Icm20948Transport.o 

C_DEPS += \
./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.d \
./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.d \
./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.d \
./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.d \
./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.d \
./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.d \
./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.d \
./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.d \
./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.d \
./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.d \
./Invn/Devices/Drivers/Icm20948/Icm20948Setup.d \
./Invn/Devices/Drivers/Icm20948/Icm20948Transport.d 


# Each subdirectory must supply rules for building sources it contributes
Invn/Devices/Drivers/Icm20948/Icm20948Augmented.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Augmented.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948Setup.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Setup.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/Devices/Drivers/Icm20948/Icm20948Transport.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices/Drivers/Icm20948/Icm20948Transport.c Invn/Devices/Drivers/Icm20948/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Invn-2f-Devices-2f-Drivers-2f-Icm20948

clean-Invn-2f-Devices-2f-Drivers-2f-Icm20948:
	-$(RM) ./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.d ./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.o ./Invn/Devices/Drivers/Icm20948/Icm20948Augmented.su ./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.d ./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.o ./Invn/Devices/Drivers/Icm20948/Icm20948AuxCompassAkm.su ./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.d ./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.o ./Invn/Devices/Drivers/Icm20948/Icm20948AuxTransport.su ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.d ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.o ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseControl.su ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.d ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.o ./Invn/Devices/Drivers/Icm20948/Icm20948DataBaseDriver.su ./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.d ./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.o ./Invn/Devices/Drivers/Icm20948/Icm20948DataConverter.su ./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.d ./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.o ./Invn/Devices/Drivers/Icm20948/Icm20948Dmp3Driver.su ./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.d ./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.o ./Invn/Devices/Drivers/Icm20948/Icm20948LoadFirmware.su ./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.d ./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.o ./Invn/Devices/Drivers/Icm20948/Icm20948MPUFifoControl.su ./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.d ./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.o ./Invn/Devices/Drivers/Icm20948/Icm20948SelfTest.su ./Invn/Devices/Drivers/Icm20948/Icm20948Setup.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948Setup.d ./Invn/Devices/Drivers/Icm20948/Icm20948Setup.o ./Invn/Devices/Drivers/Icm20948/Icm20948Setup.su ./Invn/Devices/Drivers/Icm20948/Icm20948Transport.cyclo ./Invn/Devices/Drivers/Icm20948/Icm20948Transport.d ./Invn/Devices/Drivers/Icm20948/Icm20948Transport.o ./Invn/Devices/Drivers/Icm20948/Icm20948Transport.su

.PHONY: clean-Invn-2f-Devices-2f-Drivers-2f-Icm20948

