################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/DataConverter.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/ErrorHelper.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvBasicMath.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvCksum.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvFormat.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvList.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvPrintf.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvProtocol.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvQueue.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvScheduler.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/Logger.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/Message.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/RingByteBuffer.c \
C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/UartTxEmulator.c 

OBJS += \
./Invn/EmbUtils/DataConverter.o \
./Invn/EmbUtils/ErrorHelper.o \
./Invn/EmbUtils/InvBasicMath.o \
./Invn/EmbUtils/InvCksum.o \
./Invn/EmbUtils/InvFormat.o \
./Invn/EmbUtils/InvList.o \
./Invn/EmbUtils/InvPrintf.o \
./Invn/EmbUtils/InvProtocol.o \
./Invn/EmbUtils/InvQueue.o \
./Invn/EmbUtils/InvScheduler.o \
./Invn/EmbUtils/Logger.o \
./Invn/EmbUtils/Message.o \
./Invn/EmbUtils/RingByteBuffer.o \
./Invn/EmbUtils/UartTxEmulator.o 

C_DEPS += \
./Invn/EmbUtils/DataConverter.d \
./Invn/EmbUtils/ErrorHelper.d \
./Invn/EmbUtils/InvBasicMath.d \
./Invn/EmbUtils/InvCksum.d \
./Invn/EmbUtils/InvFormat.d \
./Invn/EmbUtils/InvList.d \
./Invn/EmbUtils/InvPrintf.d \
./Invn/EmbUtils/InvProtocol.d \
./Invn/EmbUtils/InvQueue.d \
./Invn/EmbUtils/InvScheduler.d \
./Invn/EmbUtils/Logger.d \
./Invn/EmbUtils/Message.d \
./Invn/EmbUtils/RingByteBuffer.d \
./Invn/EmbUtils/UartTxEmulator.d 


# Each subdirectory must supply rules for building sources it contributes
Invn/EmbUtils/DataConverter.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/DataConverter.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/ErrorHelper.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/ErrorHelper.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvBasicMath.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvBasicMath.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvCksum.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvCksum.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvFormat.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvFormat.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvList.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvList.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvPrintf.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvPrintf.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvProtocol.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvProtocol.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvQueue.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvQueue.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/InvScheduler.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/InvScheduler.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/Logger.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/Logger.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/Message.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/Message.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/RingByteBuffer.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/RingByteBuffer.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"
Invn/EmbUtils/UartTxEmulator.o: C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/EmbUtils/UartTxEmulator.c Invn/EmbUtils/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m0plus -std=gnu11 -g3 -DDEBUG -DNUCLEO_WB09KE -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -DSTM32WB09 -c -I../../Core/Inc -I"C:/Users/jonac/Documents/GitHub/Plant-Sensor/V2/Software/BLE_Beacon/Invn/Devices" -I../../STM32_BLE/App -I../../Core/Config -I../../STM32_BLE/Target -I../../System/Config/Debug_GPIO -I../../System/Interfaces -I../../System/Modules -I../../System/Modules/Flash -I../../System/Modules/NVMDB/Inc -I../../System/Modules/PKAMGR/Inc -I../../System/Modules/Profiles/Inc -I../../System/Modules/RADIO_utils/Inc -I../../System/Modules/RTDebug -I../../System/Startup -I../../Utilities/trace/adv_trace -I../../Drivers/STM32WB0x_HAL_Driver/Inc -I../../Drivers/STM32WB0x_HAL_Driver/Inc/Legacy -I../../Utilities/misc -I../../Utilities/sequencer -I../../Utilities/lpm/tiny_lpm -I../../Middlewares/ST/STM32_BLE -I../../Drivers/CMSIS/Device/ST/STM32WB0X/Include -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CBC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/CMAC -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/Common -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc/AES/ECB -I../../Middlewares/ST/STM32_BLE/evt_handler/inc -I../../Middlewares/ST/STM32_BLE/queued_writes/inc -I../../Middlewares/ST/STM32_BLE/stack/include -I../../Drivers/CMSIS/Include -I../../Drivers/BSP/STM32WB0x-nucleo -I../../Middlewares/ST/STM32_BLE/cryptolib/Inc -I../../../../../Projects/Common/BLE/Interfaces -I../../../../../Projects/Common/BLE/Modules -I../../../../../Projects/Common/BLE/Modules/RTDebug -I../../../../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../../../../Projects/Common/BLE/Modules/Profiles/Inc -I../../../../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../../../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../../../../Projects/Common/BLE/Modules/Flash -I../../../../../Projects/Common/BLE/Startup -I../../Projects/Common/BLE/Interfaces -I../../Projects/Common/BLE/Modules -I../../Projects/Common/BLE/Modules/RTDebug -I../../Projects/Common/BLE/Modules/RADIO_utils/Inc -I../../Projects/Common/BLE/Modules/Profiles/Inc -I../../Projects/Common/BLE/Modules/PKAMGR/Inc -I../../Projects/Common/BLE/Modules/NVMDB/Inc -I../../Projects/Common/BLE/Modules/Flash -I../../Projects/Common/BLE/Startup -O0 -ffunction-sections -fdata-sections -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfloat-abi=soft -mthumb -o "$@"

clean: clean-Invn-2f-EmbUtils

clean-Invn-2f-EmbUtils:
	-$(RM) ./Invn/EmbUtils/DataConverter.cyclo ./Invn/EmbUtils/DataConverter.d ./Invn/EmbUtils/DataConverter.o ./Invn/EmbUtils/DataConverter.su ./Invn/EmbUtils/ErrorHelper.cyclo ./Invn/EmbUtils/ErrorHelper.d ./Invn/EmbUtils/ErrorHelper.o ./Invn/EmbUtils/ErrorHelper.su ./Invn/EmbUtils/InvBasicMath.cyclo ./Invn/EmbUtils/InvBasicMath.d ./Invn/EmbUtils/InvBasicMath.o ./Invn/EmbUtils/InvBasicMath.su ./Invn/EmbUtils/InvCksum.cyclo ./Invn/EmbUtils/InvCksum.d ./Invn/EmbUtils/InvCksum.o ./Invn/EmbUtils/InvCksum.su ./Invn/EmbUtils/InvFormat.cyclo ./Invn/EmbUtils/InvFormat.d ./Invn/EmbUtils/InvFormat.o ./Invn/EmbUtils/InvFormat.su ./Invn/EmbUtils/InvList.cyclo ./Invn/EmbUtils/InvList.d ./Invn/EmbUtils/InvList.o ./Invn/EmbUtils/InvList.su ./Invn/EmbUtils/InvPrintf.cyclo ./Invn/EmbUtils/InvPrintf.d ./Invn/EmbUtils/InvPrintf.o ./Invn/EmbUtils/InvPrintf.su ./Invn/EmbUtils/InvProtocol.cyclo ./Invn/EmbUtils/InvProtocol.d ./Invn/EmbUtils/InvProtocol.o ./Invn/EmbUtils/InvProtocol.su ./Invn/EmbUtils/InvQueue.cyclo ./Invn/EmbUtils/InvQueue.d ./Invn/EmbUtils/InvQueue.o ./Invn/EmbUtils/InvQueue.su ./Invn/EmbUtils/InvScheduler.cyclo ./Invn/EmbUtils/InvScheduler.d ./Invn/EmbUtils/InvScheduler.o ./Invn/EmbUtils/InvScheduler.su ./Invn/EmbUtils/Logger.cyclo ./Invn/EmbUtils/Logger.d ./Invn/EmbUtils/Logger.o ./Invn/EmbUtils/Logger.su ./Invn/EmbUtils/Message.cyclo ./Invn/EmbUtils/Message.d ./Invn/EmbUtils/Message.o ./Invn/EmbUtils/Message.su ./Invn/EmbUtils/RingByteBuffer.cyclo ./Invn/EmbUtils/RingByteBuffer.d ./Invn/EmbUtils/RingByteBuffer.o ./Invn/EmbUtils/RingByteBuffer.su ./Invn/EmbUtils/UartTxEmulator.cyclo ./Invn/EmbUtils/UartTxEmulator.d ./Invn/EmbUtils/UartTxEmulator.o ./Invn/EmbUtils/UartTxEmulator.su

.PHONY: clean-Invn-2f-EmbUtils

